language: node_js
node_js:
- '0.11'
- '0.10'
cache:
  directories:
  - mrbc
  - mruby
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - "/^v?[0-9](\\.[0-9])*/"
before_script:
- npm run compile
script:
- npm run lint
