language: node_js
node_js:
- 5
- 6
cache:
  directories:
  - mrbc
  - mruby
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - "/^v?[0-9](\\.[0-9])*/"
script:
- npm run lint
- npm test
after_success:
- npm run cover
- bash <(curl -s https://codecov.io/bash)
